### ISSUE TITLE
Issue after reboot...

### ISSUE THREAD

**Issue by rashuge** [RyanEwen/octoeverywhere_bambu_docker#2]
I got the docker working without issue.  Then I needed to update a couple of other packages and I had to reload my different Docker images and this being one of them.  It failed to work.  I now get an error message: 

![Screenshot 2024-05-10 094528](https://github.com/RyanEwen/octoeverywhere_bambu_docker/assets/42649583/a467abb4-9f30-446b-88e7-56c7dd1a8b67)

**Comment by RyanEwen** [comment]
Hi @rashuge , I haven't run into this but I would suggest removing the printers from your OctoEverywhere account and then recreating the containers and re-linking them to your OctoEverywhere account. 

To recreate the containers, run `docker-compose up -d --force-recreate`.

**Comment by RyanEwen** [comment]
Actually I think I know what might be causing this.. I'll report back shortly.

**Comment by RyanEwen** [comment]
Alright this is fixed now - you will unfortunately need to recreate your containers still, but hopefully never again after this.
1. `docker-compose down` to stop and remove the problem containers.
2. Remove your Bambu printers from https://octoeverywhere.com/account
3. `docker-compose pull` to get the latest image with the fix.
4. `docker-compose up -d --force-recreate` to recreate the containers (`--force-recreate` shouldn't be needed since `down` was used, but doesn't hurt).
5. Wait a bit and then try `docker-compose logs | grep https://octoeverywhere.com/getstarted` to link the printers to OctoEverywhere.

The issue was that the install script was being run instead of the start script, after the containers were stopped and started. https://github.com/RyanEwen/octoeverywhere_bambu_docker/commit/de352e100961ef1830052ff23106807ad47ed882
